{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "motivated-dominican",
   "metadata": {},
   "source": [
    "# Introduction to computer programming - Assignment 2025\n",
    "\n",
    "**This assignment is due at the beginning of term 1 of year 2 (exact date to be communicated in early October 2025).**\n",
    "\n",
    "**6 marks are attainable counting towards a percentage of the Practical Chemistry 2 module.**"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "87896b96",
   "metadata": {},
   "source": [
    "## SMILES of fatty acids\n",
    "\n",
    "The [XYZ file format](https://en.wikipedia.org/wiki/XYZ_file_format#Format) is a common simple format used in computational chemistry to represent molecular structures. It includes information about atom positions, but it does not explicitly contain information about atom connectivity.\n",
    "\n",
    "[SMILES strings](https://www.daylight.com/meetings/summerschool98/course/dave/smiles-intro.html) are commonly used in chemoinformatics and in machine learning studies to represent different molecules. SMILES strings contain information about atom connectivity, but they have no information about molecular structure.\n",
    "\n",
    "The goal of this assignment is to write a stand alone python script that asks the user for the file name (or path) of an XYZ file with a fatty acid molecular structure (note that the '.xyz' extension is part of the filename and should be input by the user), and after the user inputs the file name, the program outputs the SMILES string of the corresponding molecule in the file. You may assume that the fatty acid has only one unbranched potentially unsaturated hydrocarbon chain. *The output SMILES should not include the specific steriochemistry of double bonds.* You should not assume any specific atom ordering in the file.\n",
    "\n",
    "The program can output any lines of text above or below, but it must output the SMILES string in its own line and starting with the acid group. For example for butanoic acid the output should be:\n",
    "\n",
    "    OC(=O)CCC"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "b4cae516",
   "metadata": {},
   "source": [
    "XYZ files contain information about atom position only, and information about chemical bonds needs to be inferred from the distance between atoms. We will consider that two atoms are bonded if their interatomic distance is not greater than the sum of the covalent radii of the atoms involved by more than 0.4&nbsp;&Aring;. Accompanying this notebook you will find the file cov_radii.py containing covalent radii of all elements up to Oganesson. The file contains a dictionary called `cov_dictionary` and a list called `cov_list`, both contain the same information but on a different format. It is simpler to obtain the covalent radius for an element from the dictionary. For example, for nitrogen one would do:\n",
    "\n",
    "    from cov_radii import *\n",
    "    cov_dictionary[\"N\"]\n",
    "    \n",
    "If you don't feel comfortable using dictionaries, you can use the `cov_list`, where each element is of the form \\[element_symbol_string,cov_radius\\] (you can open the file cov_radii.py on a text editor and see for yourself)."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "f0c2c693",
   "metadata": {},
   "source": [
    "Along with this notebook you will find 2 XYZ files with fatty acids molecules. Any program implementation producing the correct result for these two files, and two other blind test files, will be awarded full marks."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "24d3a5b1",
   "metadata": {
    "jp-MarkdownHeadingCollapsed": true
   },
   "source": [
    "### Suggested implementation\n",
    "\n",
    "Use the template in file xyz2smiles.py to structure your program.\n",
    "\n",
    "It is possible to assemble a working program by implementing and using the functions below. Partial marks will be awarded, **1 mark** for structuring your code using function defined with meaningful docstrings, and for a working implementation of the following functions.\n",
    "\n",
    "#### parse_line(*number*,*string*) - (1 mark)\n",
    "\n",
    "This function receives one integer number and one string (a line of the XYZ file) as its arguments, and return a list of the form:\n",
    "\n",
    "    [atom_label,element_symbol,coordinate_list]\n",
    "\n",
    "where atom_label is an integer corresponding to the function argument, element_symbol is a string with the chemical symbol letter(s) and coordinate_list is a list of numbers with the atom coordinates. For example:\n",
    "\n",
    "    [12,'As',[66.52700,-0.24800,33.94300]]\n",
    "    \n",
    "\n",
    "#### distance(*list1*,*list2*) - 1 mark\n",
    "\n",
    "This function receives two lists as arguments, each array containing the coordinates of a point in 3D space. The function should return the distance between these two points in space.\n",
    "\n",
    "\n",
    "#### coordination(*list1*,*list2*) - (1 mark)\n",
    "\n",
    "This function receives two lists as arguments. list2 is a list of lists and includes list1. list1 and the sublists of list2 are of the form of the output of `parse_line`. The function returns a list with the elements of list2 corresponding to atoms which are bonded to the atom in list1. The output list should not include list1.\n",
    "\n",
    "\n",
    "#### is_acid(*list1*,*list2*) - (0.5 marks)\n",
    "\n",
    "This function receives two lists. list1 corresponds to a carbon atom and has the same form as the output of the `parse_line` function. lists2 has the same form as the output of the `coordination` function with information about the atoms in the coordination sphere of the atom in list1. The function returns a boolean depending on whether the atom is part of a carboxyl group or not.\n",
    "\n",
    "\n",
    "#### is_terminal(*list1*,*list2*) - (0.5 marks)\n",
    "\n",
    "This function receives two lists. list1 corresponds to a carbon atom and has the same form as the output of the `parse_line` function. lists2 has the same form as the output of the `coordination` function with information about the atoms in the coordination sphere of the atom in list1. The function returns a boolean depending on whether the atom is a terminal atom in the aliphatic chain.\n",
    "\n",
    "\n",
    "#### unsaturation(*list1*,*list2*) - (1 mark)\n",
    "\n",
    "This function receives two lists. list1 corresponds to a carbon atom and has the same form as the output of the `parse_line` function. lists2 has the same form as the output of the `coordination` function with information about the atoms in the coordination sphere of the atom in list1. The function returns the number of double bond equivalents the atom in list1 is involved in: 0 if the carbon atom is saturated, 1 if involved in one double bond, or 2 if involved in two double bonds or a triple bond."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "d293e210",
   "metadata": {},
   "source": [
    "### Testing your program\n",
    "\n",
    "This assignment is drafted in a similar way to how the program specifications would be written in a professional programming assignment. The program specification document outlines the details of how the *client* expects the program to work, and the final *product* is assessed against the criteria enunciated in that document. Similarly, in this assignment your program will be assessed against the criteria detailed above.\n",
    "\n",
    "The output of your program will be compared to the expected output for the two open test files, and two blind test files, and in case of match **6 marks** are awarded.\n",
    "\n",
    "It is important that the output of the program follows the format described. These formatting elements will be used while processing the output of the program.\n",
    "\n",
    "If a user is not able to trust the results of your program, he or she may still want to use the functions you have defined for writing his or her own code. In such case, the user will be importing your functions and will be expecting them to work as outlined in the \"Suggested implementation\". (In technical terms, the \"Suggested implementation\" is defining an [Application Programming Interface: API](https://en.wikipedia.org/wiki/API)).\n",
    "\n",
    "If your program does not output the expected results for the test files used, but one is able to import the functions defined within it, these will be tested against the suggested implementation for partial marks. *Make sure you can import the functions you have defined*. Make sure that the functions are named and receive arguments as per suggest implementation."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1681fb63-48fc-400b-b44c-cfbe76eb90f0",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Function: parse_line\n",
    "# This function reads a line from a molecular coordinate file and extracts atom information.\n",
    "\n",
    "def parse_line(number, string):\n",
    "    parts = string.split() \n",
    "    element_symbol = parts[0]  \n",
    "    x, y, z = map(float, parts[1:])  \n",
    "    return [number, element_symbol, [x, y, z]]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2d195f1a-969c-40b4-b0d3-d95aae808159",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Function: distance\n",
    "# This function calculates the Euclidean distance between two 3D points.\n",
    "# It expects both inputs (list1, list2) to be lists (or tuples) of three numeric values [x, y, z].\n",
    "# The formula used is sqrt((x2-x1)^2 + (y2-y1)^2 + (z2-z1)^2).\n",
    "# If inputs are invalid (wrong type, missing values, etc.), it will print an error and return None.\n",
    "# Assumption: Both lists represent valid 3D coordinates of atoms.\n",
    "\n",
    "def distance(list1, list2):\n",
    "    try:\n",
    "        return math.sqrt(\n",
    "            (list2[0]- list1[0])**2 +\n",
    "            (list2[1]- list1[1])**2 +\n",
    "            (list2[2]- list1[2])**2\n",
    "        )\n",
    "    except (IndexError, TypeError, NameError) as e:\n",
    "        print(f\"Error: {e}\")\n",
    "        return None"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "731e2c67-215d-47c8-9631-49dbc62fdcc1",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Function: coordination\n",
    "# This function determines which atoms are bonded to a given atom.\n",
    "# It compares the distance between the given atom (list1) and every other atom in list2.\n",
    "# Bonding rule: if the distance between the two atoms is less than or equal to\n",
    "# the sum of their covalent radii (from cov_dictionary) plus a tolerance (0.4 Å), \n",
    "# they are considered bonded.\n",
    "# It returns a list of atoms that are bonded to the given atom.\n",
    "# Assumption: list1 and atoms in list2 follow the structure [id, element_symbol, [x, y, z]],\n",
    "# and cov_dictionary contains the covalent radii for all possible element symbols.\n",
    "\n",
    "def coordination(list1, list2):\n",
    "    bonded_atoms = []\n",
    "    for atom in list2:\n",
    "        if atom == list1:\n",
    "            continue\n",
    "        r1 = cov_dictionary[list1[1]]\n",
    "        r2 = cov_dictionary[atom[1]]\n",
    "        d = distance(list1[2], atom[2])\n",
    "        if d <= r1 + r2 + 0.4:\n",
    "            bonded_atoms.append(atom)\n",
    "    return bonded_atoms"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "588b60c8-0dd4-42c6-98d5-d3f6c806d67f",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Function: is_acid\n",
    "# This function checks if a given carbon atom is part of a carboxylic acid group.\n",
    "# It only applies if the central atom (list1) is a carbon (\"C\").\n",
    "# The function looks at all bonded atoms (list2). If at least two oxygen (\"O\") atoms\n",
    "# are directly bonded to the carbon, it classifies the atom as being in an acid group.\n",
    "# Returns True if the carbon has ≥ 2 oxygen neighbors, otherwise False.\n",
    "# Assumptions:\n",
    "# - list1 follows the format [id, element_symbol, [x, y, z]].\n",
    "# - list2 is the list of neighboring atoms (e.g., from coordination()).\n",
    "# - Only carboxyl-like structures with ≥ 2 oxygen atoms are considered \"acid.\"\n",
    "\n",
    "def is_acid(list1, list2):\n",
    "    oxygens = []\n",
    "    if list1[1] != \"C\": \n",
    "        return False\n",
    "    for atom in list2:\n",
    "        if atom[1] == \"O\":\n",
    "            oxygens.append(atom)\n",
    "    if len(oxygens) >= 2:\n",
    "        oxygens.append(list1)\n",
    "        return True\n",
    "    else:\n",
    "        return False"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "55297dca-2476-492d-a7a4-0f008ae26313",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Function: is_terminal\n",
    "# This function checks whether a carbon atom is a terminal carbon (at the end of a chain).\n",
    "# A terminal carbon is defined here as a carbon atom bonded to either:\n",
    "# - only one other carbon atom, OR\n",
    "# - no other carbon atoms at all.\n",
    "# Returns True if the carbon is terminal, False otherwise.\n",
    "# Assumptions:\n",
    "# - list1 is in the format [id, element_symbol, [x, y, z]].\n",
    "# - list2 is the list of neighboring atoms (from coordination()).\n",
    "# - Only carbon atoms (\"C\") are tested. If list1 is not carbon, the function immediately returns False.\n",
    "\n",
    "def is_terminal(list1, list2):\n",
    "    if list1[1] != \"C\":\n",
    "        return False \n",
    "    carbon_count = 0\n",
    "    for atom in list2:\n",
    "        if atom[1] == \"C\":\n",
    "            carbon_count += 1\n",
    "    if carbon_count == 1:\n",
    "        return True\n",
    "    elif carbon_count == 0:\n",
    "        return True\n",
    "    else:\n",
    "        return False"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4e777bf7-2c3e-4ce7-bd39-15a064180e92",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Function: unsaturation\n",
    "# This function estimates the degree of unsaturation (bond order) for a carbon atom.\n",
    "# It looks at the number and type of atoms bonded to the carbon.\n",
    "# Logic:\n",
    "# - If 4 neighbors → return 0 (fully saturated, single bonds).\n",
    "# - If 3 neighbors (including 1 C and 2 O) → return 1 (carboxyl group-like unsaturation).\n",
    "# - If 3 neighbors (general case) → return 1 (double bond implied).\n",
    "# - If 2 neighbors → return 2 (triple bond implied).\n",
    "# - Otherwise, return None (not applicable).\n",
    "# Assumptions:\n",
    "# - list1 is a carbon atom entry [id, \"C\", [x, y, z]].\n",
    "# - list2 is its bonded atoms (from coordination()).\n",
    "# - The classification is simplified and does not cover all chemical cases.\n",
    "\n",
    "def unsaturation(list1, list2):\n",
    "    if list1[1] != 'C':\n",
    "        return None\n",
    "\n",
    "    saturation_bag = [atom[1] for atom in list2]\n",
    "\n",
    "    if len(saturation_bag) == 4:\n",
    "        return 0  \n",
    "\n",
    "    elif len(saturation_bag) == 3 and saturation_bag.count('C') == 1 and saturation_bag.count('O') == 2:\n",
    "        return 1  \n",
    "\n",
    "    elif len(saturation_bag) == 3:\n",
    "        return 1  \n",
    "\n",
    "    elif len(saturation_bag) == 2:\n",
    "        return 2  \n",
    "\n",
    "    else:\n",
    "        return None"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "025193fe-4947-4af3-951f-9b651637b1d6",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Function: smiles\n",
    "# This function generates a simplified SMILES (Simplified Molecular Input Line Entry System) string\n",
    "# representation of the molecule.\n",
    "# Process:\n",
    "# - Starts by finding a carbon atom that is part of a carboxylic acid group (is_acid).\n",
    "#   If found, it initializes the string with \"OC(=O)\".\n",
    "# - Traverses carbon atoms in a chain-like manner, using unsaturation() to decide whether to\n",
    "#   represent bonds as single (\"C\"), double (\"C=\"), or triple (\"C#\").\n",
    "# - Stops when it reaches a terminal carbon (is_terminal).\n",
    "# - Builds the SMILES string step by step, simulating traversal along the carbon chain.\n",
    "# Returns: a string representing the simplified SMILES notation.\n",
    "# Assumptions:\n",
    "# - Input is a list of atoms in format [id, element_symbol, [x, y, z]].\n",
    "# - Focuses mainly on linear carbon chains and carboxylic acid groups.\n",
    "# - Does not handle branching or more complex structures.\n",
    "\n",
    "def smiles(atoms):\n",
    "    smiles_str = \"\"\n",
    "\n",
    "    start_atom = None\n",
    "    start_neighbours = None\n",
    "    for atom in atoms:\n",
    "        if atom[1] == \"C\":\n",
    "            bonds = coordination(atom, atoms)\n",
    "            if is_acid(atom, bonds):\n",
    "                smiles_str += \"OC(=O)\"\n",
    "                start_atom = atom\n",
    "                start_neighbours = bonds\n",
    "                break\n",
    "    \n",
    "    if start_atom is None:\n",
    "        return smiles_str  \n",
    "    \n",
    "    next_atom = None\n",
    "    for n in start_neighbours:\n",
    "        if n[1] == \"C\":\n",
    "            next_atom = n\n",
    "            next_neighbours = coordination(n, atoms)\n",
    "            break\n",
    "    \n",
    "    if next_atom is None:\n",
    "        return smiles_str  \n",
    "\n",
    "    prev_atom = start_atom\n",
    "    prev_neighbours = start_neighbours\n",
    "    curr_atom = next_atom\n",
    "    curr_neighbours = next_neighbours\n",
    "\n",
    "    while True:\n",
    "        u_prev = unsaturation(prev_atom, prev_neighbours)\n",
    "        u_curr = unsaturation(curr_atom, curr_neighbours)\n",
    "\n",
    "        if u_curr == 0:\n",
    "            smiles_str += \"C\"\n",
    "        elif u_prev == 1 and u_curr == 1:\n",
    "            smiles_str += \"C\"\n",
    "        elif u_prev == 0 and u_curr == 1:\n",
    "            smiles_str += \"C=\"\n",
    "        elif u_prev == 0 and u_curr == 2:\n",
    "            smiles_str += \"C#\"\n",
    "        else:\n",
    "            smiles_str += \"C\"\n",
    "\n",
    "        if is_terminal(curr_atom, curr_neighbours):\n",
    "            break\n",
    "\n",
    "        track_prev = prev_atom\n",
    "        prev_atom = curr_atom\n",
    "        prev_neighbours = curr_neighbours\n",
    "\n",
    "        next_atom = None\n",
    "        for n in curr_neighbours:\n",
    "            if n[1] == \"C\" and n != track_prev:\n",
    "                next_atom = n\n",
    "                next_neighbours = coordination(n, atoms)\n",
    "                break\n",
    "\n",
    "        if next_atom is None:\n",
    "            smiles_str += \"C\"\n",
    "            break\n",
    "\n",
    "        curr_atom = next_atom\n",
    "        curr_neighbours = next_neighbours\n",
    "\n",
    "    return smiles_str"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 168,
   "id": "6349c43f-3d9e-41ff-a1eb-c8acd97bec9d",
   "metadata": {},
   "outputs": [
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Enter a file:  hexanoic.xyz\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "SMILES: OC(=O)CCCCC\n"
     ]
    }
   ],
   "source": [
    "import math\n",
    "from cov_radii import cov_dictionary\n",
    "\n",
    "def parse_line(number, string):\n",
    "    parts = string.split() \n",
    "    element_symbol = parts[0]  \n",
    "    x, y, z = map(float, parts[1:])  \n",
    "    return [number, element_symbol, [x, y, z]]\n",
    "\n",
    "def distance(list1, list2):\n",
    "    try:\n",
    "        return math.sqrt(\n",
    "            (list2[0]- list1[0])**2 +\n",
    "            (list2[1]- list1[1])**2 +\n",
    "            (list2[2]- list1[2])**2\n",
    "        )\n",
    "    except (IndexError, TypeError, NameError) as e:\n",
    "        print(f\"Error: {e}\")\n",
    "        return None\n",
    "\n",
    "def coordination(list1, list2):\n",
    "    bonded_atoms = []\n",
    "    for atom in list2:\n",
    "        if atom == list1:\n",
    "            continue\n",
    "        r1 = cov_dictionary[list1[1]]\n",
    "        r2 = cov_dictionary[atom[1]]\n",
    "        d = distance(list1[2], atom[2])\n",
    "        if d <= r1 + r2 + 0.4:\n",
    "            bonded_atoms.append(atom)\n",
    "    return bonded_atoms\n",
    "\n",
    "def is_acid(list1, list2):\n",
    "    oxygens = []\n",
    "    if list1[1] != \"C\": \n",
    "        return False\n",
    "    for atom in list2:\n",
    "        if atom[1] == \"O\":\n",
    "            oxygens.append(atom)\n",
    "    if len(oxygens) >= 2:\n",
    "        oxygens.append(list1)\n",
    "        return True\n",
    "    else:\n",
    "        return False\n",
    "\n",
    "def is_terminal(list1, list2):\n",
    "    if list1[1] != \"C\":\n",
    "        return False \n",
    "    carbon_count = 0\n",
    "    for atom in list2:\n",
    "        if atom[1] == \"C\":\n",
    "            carbon_count += 1\n",
    "    if carbon_count == 1:\n",
    "        return True\n",
    "    elif carbon_count == 0:\n",
    "        return True\n",
    "    else:\n",
    "        return False\n",
    "\n",
    "def unsaturation(list1, list2):\n",
    "    if list1[1] != 'C':\n",
    "        return None\n",
    "\n",
    "    saturation_bag = [atom[1] for atom in list2]\n",
    "\n",
    "    if len(saturation_bag) == 4:\n",
    "        return 0  \n",
    "\n",
    "    elif len(saturation_bag) == 3 and saturation_bag.count('C') == 1 and saturation_bag.count('O') == 2:\n",
    "        return 1  \n",
    "\n",
    "    elif len(saturation_bag) == 3:\n",
    "        return 1  \n",
    "\n",
    "    elif len(saturation_bag) == 2:\n",
    "        return 2  \n",
    "\n",
    "    else:\n",
    "        return None\n",
    "\n",
    "def smiles(atoms):\n",
    "    smiles_str = \"\"\n",
    "\n",
    "    start_atom = None\n",
    "    start_neighbours = None\n",
    "    for atom in atoms:\n",
    "        if atom[1] == \"C\":\n",
    "            bonds = coordination(atom, atoms)\n",
    "            if is_acid(atom, bonds):\n",
    "                smiles_str += \"OC(=O)\"\n",
    "                start_atom = atom\n",
    "                start_neighbours = bonds\n",
    "                break\n",
    "    \n",
    "    if start_atom is None:\n",
    "        return smiles_str  \n",
    "    \n",
    "    next_atom = None\n",
    "    for n in start_neighbours:\n",
    "        if n[1] == \"C\":\n",
    "            next_atom = n\n",
    "            next_neighbours = coordination(n, atoms)\n",
    "            break\n",
    "    \n",
    "    if next_atom is None:\n",
    "        return smiles_str  \n",
    "\n",
    "    prev_atom = start_atom\n",
    "    prev_neighbours = start_neighbours\n",
    "    curr_atom = next_atom\n",
    "    curr_neighbours = next_neighbours\n",
    "\n",
    "    while True:\n",
    "        u_prev = unsaturation(prev_atom, prev_neighbours)\n",
    "        u_curr = unsaturation(curr_atom, curr_neighbours)\n",
    "\n",
    "        if u_curr == 0:\n",
    "            smiles_str += \"C\"\n",
    "        elif u_prev == 1 and u_curr == 1:\n",
    "            smiles_str += \"C\"\n",
    "        elif u_prev == 0 and u_curr == 1:\n",
    "            smiles_str += \"C=\"\n",
    "        elif u_prev == 0 and u_curr == 2:\n",
    "            smiles_str += \"C#\"\n",
    "        else:\n",
    "            smiles_str += \"C\"\n",
    "\n",
    "        if is_terminal(curr_atom, curr_neighbours):\n",
    "            break\n",
    "\n",
    "        track_prev = prev_atom\n",
    "        prev_atom = curr_atom\n",
    "        prev_neighbours = curr_neighbours\n",
    "\n",
    "        next_atom = None\n",
    "        for n in curr_neighbours:\n",
    "            if n[1] == \"C\" and n != track_prev:\n",
    "                next_atom = n\n",
    "                next_neighbours = coordination(n, atoms)\n",
    "                break\n",
    "\n",
    "        if next_atom is None:\n",
    "            smiles_str += \"C\"\n",
    "            break\n",
    "\n",
    "        curr_atom = next_atom\n",
    "        curr_neighbours = next_neighbours\n",
    "\n",
    "    return smiles_str\n",
    "\n",
    "def main():\n",
    "    file_path = input(\"Enter a file: \")\n",
    "    atoms = []\n",
    "    atoms1 = []\n",
    "    try:\n",
    "        with open(file_path, \"r\") as file:\n",
    "            lines = file.readlines()\n",
    "        i = 1  \n",
    "        for line in lines[2:]: \n",
    "            atom = parse_line(i, line)\n",
    "            atom1 = parse_line1(i, line)\n",
    "            atoms.append(atom)\n",
    "            atoms1.append(atom1)\n",
    "            i += 1\n",
    "        bonds = coordination(atoms[1], atoms[:])\n",
    "        acid = is_acid(atoms[1], bonds)\n",
    "        terminal = is_terminal(atoms[1], bonds)\n",
    "        saturation = unsaturation(atoms[1], bonds)\n",
    "        smiles_string = smiles(atoms)\n",
    "        print(\"SMILES:\", smiles_string)\n",
    "\n",
    "    except FileNotFoundError:\n",
    "        print(\"This file was not found\")\n",
    "if __name__ == \"__main__\":\n",
    "    main()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
